### ISSUE TITLE
Pb when Toggling Menu

### ISSUE THREAD

**Issue by ghazal** [ceford/j4xdemos-com-jdocmanual#1]
### First and foremost, your component is great and very useful. TKS!

---

![jdocs_manual_toggle_menu](https://user-images.githubusercontent.com/490245/141643977-daf4f987-046b-4080-8c39-93b3ae5e9bfa.png)

As you can see, when Toggling (joomla core) Menu, the list disappears.

---
When Toggling **YOUR** menu, everything is OK, see below:

![jdocs_manual_toggle_menu2](https://user-images.githubusercontent.com/490245/141644106-ba8ac0fc-8d9a-4ef9-bb69-b9cc5e2ef194.png)
---
---
Nothing mind-blowing, but as a laptop user (13" Mac Powerbook), my first move is always to toggle the core menu.

**Comment by ceford** [comment]
I have changed the menu. Uninstall, logout/login, get the latest download and install. Thanks for your comments.

**Comment by ceford** [comment]
https://github.com/ceford/j4xdemos-com-jdocmanual/archive/refs/heads/master.zip

**Comment by ceford** [comment]
Sorry I have not attended to this for so long. I have made a lot of changes recently. Best to remove the previous installation and start again with the latest code.
