### ISSUE TITLE
Installation: Error in SQL syntax

### ISSUE THREAD

**Issue by ghost** [ceford/j4xdemos-com-jdocmanual#2]
After installation got message:

<img width="1432" alt="docmanualerror" src="https://user-images.githubusercontent.com/89642616/173224533-0f085e41-94eb-4619-b8c3-c51ac29f7f39.png">

The installation is unsuccessful. Tried installation over weeks several times without success.

#### System information

<img width="1018" alt="sys" src="https://user-images.githubusercontent.com/89642616/173224573-9828f57d-659f-4afe-b058-2666bb6833bd.png">

**Comment by ceford** [comment]
Thanks for finding that - I have fixed the bug. Please try again.

Cliff

**Comment by ghost** [comment]
Thanks for fixing the bug. I guess i have to download the "master", but can't figure out how or where to download the fixed version. Can you please give me a hint?

**Comment by ghost** [comment]
Closing as the manual is installed cause the url in https://docs.joomla.org/JDOC_Manual is the master :-)
